version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/test?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      THROUGHPUT_PER_MINUTE: 100
      JWT_SECRET: test
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
